import AdminSidebar from "@/components/AdminSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-[250px_1fr] h-[calc(100vh-68px)]">
      <AdminSidebar />
      <main className="flex-1 overflow-y-auto hide-scrollbar bg-gray-50 p-5">
        {children}
      </main>
    </div>
  );
}
