import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <body>
          <nav className="sticky top-0 z-50 bg-accent-foreground py-4 text-primary-foreground text-center font-semibold text-lg md:text-xl tracking-wide">
            Revy – Never Miss a Renewal
          </nav>
          {children}
        </body>
      </body>
    </html>
  );
}
